// TEMPORARY AUTOGENERATED FILE: easyjson stub code to make the package
// compilable during generation.

package  http

import (
  "github.com/mailru/easyjson/jwriter"
  "github.com/mailru/easyjson/jlexer"
)

func ( Category656363463View ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Category656363463View ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Category656363463View *Category656363463View

func ( Category656363463Views ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Category656363463Views ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Category656363463Views *Category656363463Views

func ( CategoryCreateRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CategoryCreateRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CategoryCreateRequest *CategoryCreateRequest

func ( CategoryUpdateRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* CategoryUpdateRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_CategoryUpdateRequest *CategoryUpdateRequest

func ( Product1899176864View ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Product1899176864View ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Product1899176864View *Product1899176864View

func ( Product1899176864Views ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Product1899176864Views ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Product1899176864Views *Product1899176864Views

func ( ProductCreateRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProductCreateRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProductCreateRequest *ProductCreateRequest

func ( ProductUpdateRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* ProductUpdateRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_ProductUpdateRequest *ProductUpdateRequest

func ( Todo2548332322View ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Todo2548332322View ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Todo2548332322View *Todo2548332322View

func ( Todo2548332322Views ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* Todo2548332322Views ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_Todo2548332322Views *Todo2548332322Views

func ( TodoCreateRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TodoCreateRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TodoCreateRequest *TodoCreateRequest

func ( TodoUpdateRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* TodoUpdateRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_TodoUpdateRequest *TodoUpdateRequest

func ( VerySecret1653553545View ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* VerySecret1653553545View ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VerySecret1653553545View *VerySecret1653553545View

func ( VerySecret1653553545Views ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* VerySecret1653553545Views ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VerySecret1653553545Views *VerySecret1653553545Views

func ( VerySecretCreateRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* VerySecretCreateRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VerySecretCreateRequest *VerySecretCreateRequest

func ( VerySecretUpdateRequest ) MarshalEasyJSON(w *jwriter.Writer) {}
func (* VerySecretUpdateRequest ) UnmarshalEasyJSON(l *jlexer.Lexer) {}

type EasyJSON_exporter_VerySecretUpdateRequest *VerySecretUpdateRequest
