// Copyright 2019-present Facebook
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Code generated by entc, DO NOT EDIT.

package http

import (
	"time"

	"entgo.io/quynguyen-todo/ent/category"
	"entgo.io/quynguyen-todo/ent/product"
	"entgo.io/quynguyen-todo/ent/schema/schematype"
	"entgo.io/quynguyen-todo/ent/todo"
)

// Payload of a ent.Category create request.
type CategoryCreateRequest struct {
	Text   *string                     `json:"text"`
	Status *category.Status            `json:"status"`
	Config **schematype.CategoryConfig `json:"config"`
	Todos  []int                       `json:"todos"`
}

// Payload of a ent.Category update request.
type CategoryUpdateRequest struct {
	Text   *string                     `json:"text"`
	Status *category.Status            `json:"status"`
	Config **schematype.CategoryConfig `json:"config"`
	Todos  []int                       `json:"todos"`
}

// Payload of a ent.Product create request.
type ProductCreateRequest struct {
	CreatedAt *time.Time      `json:"created_at"`
	Status    *product.Status `json:"status"`
	Priority  *int            `json:"priority"`
	Text      *string         `json:"text"`
}

// Payload of a ent.Product update request.
type ProductUpdateRequest struct {
	Status   *product.Status `json:"status"`
	Priority *int            `json:"priority"`
	Text     *string         `json:"text"`
}

// Payload of a ent.Todo create request.
type TodoCreateRequest struct {
	CreatedAt *time.Time   `json:"created_at"`
	Status    *todo.Status `json:"status"`
	Priority  *int         `json:"priority"`
	Text      *string      `json:"text"`
	Blob      *[]byte      `json:"blob"`
	Parent    *int         `json:"parent"`
	Children  []int        `json:"children"`
	Category  *int         `json:"category"`
	Secret    *int         `json:"secret"`
}

// Payload of a ent.Todo update request.
type TodoUpdateRequest struct {
	Status   *todo.Status `json:"status"`
	Priority *int         `json:"priority"`
	Text     *string      `json:"text"`
	Blob     *[]byte      `json:"blob"`
	Parent   *int         `json:"parent"`
	Children []int        `json:"children"`
	Category *int         `json:"category"`
	Secret   *int         `json:"secret"`
}

// Payload of a ent.VerySecret create request.
type VerySecretCreateRequest struct {
	Password *string `json:"password"`
}

// Payload of a ent.VerySecret update request.
type VerySecretUpdateRequest struct {
	Password *string `json:"password"`
}
