// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"time"

	"entgo.io/quynguyen-todo/ent/product"
	"entgo.io/quynguyen-todo/ent/user"
)

type ProductInput struct {
	Status    product.Status `json:"status"`
	CreatedAt *time.Time     `json:"createdAt"`
	Priority  *int           `json:"priority"`
	Text      string         `json:"text"`
}

type UserInput struct {
	Status       user.Status `json:"status"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	ProviderName string      `json:"provider_name"`
	ProviderID   string      `json:"provider_id"`
}
