// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graphql

import (
	"entgo.io/quynguyen-todo/ent/product"
	"entgo.io/quynguyen-todo/ent/todo"
)

type ProductInput struct {
	Status   product.Status `json:"status"`
	Priority *int           `json:"priority"`
	Text     string         `json:"text"`
}

type TodoInput struct {
	Status     todo.Status `json:"status"`
	Priority   *int        `json:"priority"`
	Text       string      `json:"text"`
	Parent     *int        `json:"parent"`
	CategoryID *int        `json:"category_id"`
}
